// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIthBEL4XtzxLPzbNpIpFan-2rfgEobBc',
    appId: '1:704656165072:web:93da2d99e492572ef536d5',
    messagingSenderId: '704656165072',
    projectId: 'smart-home-2-eb8ae',
    authDomain: 'smart-home-2-eb8ae.firebaseapp.com',
    storageBucket: 'smart-home-2-eb8ae.firebasestorage.app',
    measurementId: 'G-TWPNXSD61S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuA2M01GUyRPEGsgPnTavWifA706t-VNc',
    appId: '1:704656165072:android:6ef39741da066b63f536d5',
    messagingSenderId: '704656165072',
    projectId: 'smart-home-2-eb8ae',
    storageBucket: 'smart-home-2-eb8ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgD2lb07gL2BElgyMc0WKaKbC_XNjyiqg',
    appId: '1:704656165072:ios:f862f8bfd4c9032cf536d5',
    messagingSenderId: '704656165072',
    projectId: 'smart-home-2-eb8ae',
    storageBucket: 'smart-home-2-eb8ae.firebasestorage.app',
    iosBundleId: 'com.example.finalexam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgD2lb07gL2BElgyMc0WKaKbC_XNjyiqg',
    appId: '1:704656165072:ios:f862f8bfd4c9032cf536d5',
    messagingSenderId: '704656165072',
    projectId: 'smart-home-2-eb8ae',
    storageBucket: 'smart-home-2-eb8ae.firebasestorage.app',
    iosBundleId: 'com.example.finalexam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIthBEL4XtzxLPzbNpIpFan-2rfgEobBc',
    appId: '1:704656165072:web:83ebcdad57fe77e4f536d5',
    messagingSenderId: '704656165072',
    projectId: 'smart-home-2-eb8ae',
    authDomain: 'smart-home-2-eb8ae.firebaseapp.com',
    storageBucket: 'smart-home-2-eb8ae.firebasestorage.app',
    measurementId: 'G-3016SNLFT8',
  );

}